networks:
  application:
    driver: bridge

volumes:
  omni-pgsql-data:

services:
  laravel:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 8000:8000 # for api routing
      - 8080:8080 # for websocket
    volumes:
      - ./src:/app
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=default
      - AWS_REGION=your-region
    depends_on:
      - postgres
    networks:
      - application
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        composer install
        # composer create-project laravel/laravel .
        php artisan migrate --seed
        php artisan serve --host=0.0.0.0 --port=8000
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - omni-pgsql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=omni
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
